# Generated by Django 3.2.7 on 2021-10-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='Número do CPF')),
                ('p_nome', models.CharField(max_length=45, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=100)),
                ('dt_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('numero_rg', models.CharField(blank=True, max_length=9, null=True, verbose_name='Número do RG')),
                ('numero_ra', models.CharField(max_length=14, verbose_name='Número do RA')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('sexo', models.CharField(choices=[['F', 'Feminino'], ['M', 'Masculino'], ['N', 'Nenhuma das Opções']], max_length=1)),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id_contato', models.AutoField(primary_key=True, serialize=False)),
                ('tel_aluno', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone do Aluno')),
                ('tel_mae', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone da Mãe')),
                ('tel_pai', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone do Pai')),
                ('tel_recado', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone Recado')),
                ('num_whatsapp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Whatsapp')),
                ('email', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_cursos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45, verbose_name='Nome do Curso')),
                ('dia_semana', models.CharField(max_length=15, verbose_name='Dia da Semana')),
                ('horario', models.CharField(max_length=20, verbose_name='Horário')),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eestadual',
            fields=[
                ('id_eestadual', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Escola')),
                ('serie', models.CharField(max_length=2, verbose_name='Série')),
                ('nivel', models.CharField(choices=[['Fundamental II', 'Fundamental II'], ['Médio', 'Médio'], ['EJA', 'EJA']], max_length=15, verbose_name='Nível')),
            ],
            options={
                'db_table': 'eestadual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(choices=[['Alameda', 'Alameda'], ['Avenida', 'Avenida'], ['Chácara', 'Chácara'], ['Estrada', 'Estrada'], ['Praça', 'Praça'], ['Recanto', 'Recanto'], ['Rua', 'Rua'], ['Sítio', 'Sítio'], ['Viela', 'Viela']], max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
    ]
