# Generated by Django 3.2.8 on 2021-11-07 21:23

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF (Somente Números):')),
                ('p_nome', models.CharField(max_length=45, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=100)),
                ('dt_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('numero_rg', models.CharField(blank=True, max_length=9, null=True, verbose_name='Número do RG')),
                ('numero_ra', models.CharField(max_length=14, verbose_name='Número do RA')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('sexo', models.CharField(choices=[['F', 'Feminino'], ['M', 'Masculino'], ['N', 'Nenhuma das Opções']], max_length=1)),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_aluno', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone do Aluno')),
                ('tel_mae', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone da Mãe')),
                ('tel_pai', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone do Pai')),
                ('tel_recado', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone Recado')),
                ('num_whatsapp', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número Whatsapp')),
                ('email', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_cursos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45, verbose_name='Nome do Curso')),
                ('turma', models.CharField(max_length=3, unique=True, verbose_name='Turma')),
                ('dia_semana', models.CharField(max_length=45, verbose_name='Dia da Semana')),
                ('horario', models.CharField(max_length=25, verbose_name='Horário')),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eestadual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Escola')),
                ('serie', models.CharField(max_length=2, verbose_name='Série')),
                ('nivel', models.CharField(choices=[['Fundamental II', 'Fundamental II'], ['Médio', 'Médio'], ['EJA', 'EJA']], max_length=15, verbose_name='Nível')),
            ],
            options={
                'db_table': 'eestadual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(choices=[['Alameda', 'Alameda'], ['Avenida', 'Avenida'], ['Chácara', 'Chácara'], ['Estrada', 'Estrada'], ['Praça', 'Praça'], ['Recanto', 'Recanto'], ['Rua', 'Rua'], ['Sítio', 'Sítio'], ['Viela', 'Viela']], max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('aluno_cpf', models.CharField(db_column='Aluno_cpf', max_length=11, primary_key=True, serialize=False)),
                ('curso1', models.CharField(choices=[['Alemão', 'Alemão'], ['Espanhol', 'Espanhol'], ['Francês', 'Francês'], ['Inglês', 'Inglês'], ['Italiano', 'Italiano'], ['Japonês', 'Japonês']], max_length=45, verbose_name='Nome do Curso 1')),
                ('turma1', models.CharField(max_length=3, null=True, verbose_name='Turma')),
                ('dia_semana1', models.CharField(choices=[['Terça e Quinta', 'Alemão - Terça e Quinta'], ['Segunda e Quarta', 'Espanhol - Segunda e Quarta'], ['Terça e Quinta', 'Espanhol - Terça e Quinta'], ['Terça e Quinta', 'Francês - Terça e Quinta'], ['Terça e Quinta', 'Italiano - Terça e Quinta'], ['Segunda e Quarta', 'Inglês - Segunda e Quarta'], ['Terça e Quinta', 'Inglês - Terça e Quinta'], ['Segunda e Quarta', 'Japonês - Segunda e Quarta']], max_length=45, verbose_name='Dia da Semana')),
                ('horario1', models.CharField(choices=[['17:10 às 18:50', 'Alemão 3ª e 5ª- 17:10 às 18:50'], ['08:00 às 09:40', 'Espanhol 2ª e 4ª- 08:00 às 09:40'], ['17:10 às 18:50', 'Espanhol 2ª e 4ª- 17:10 às 18:50'], ['19:10 às 20:50', 'Espanhol 2ª e 4ª- 19:10 às 20:50'], ['15:30 às 17:10', 'Espanhol 3ª e 5ª- 15:30 às 17:10'], ['17:10 às 18:50', 'Espanhol 3ª e 5ª- 17:10 às 18:50'], ['08:00 às 09:40', 'Francês 3ª e 5ª- 08:00 às 09:40'], ['19:10 às 20:50', 'Francês 3ª e 5ª- 19:10 às 20:50'], ['13:30 às 15:10', 'Italiano 3ª e 5ª- 13:30 às 15:10'], ['17:10 às 18:50', 'Inglês 2ª e 4ª- 17:10 às 18:50'], ['19:10 às 20:50', 'Inglês 2ª e 4ª- 19:10 às 20:50'], ['09:40 às 11:20', 'Inglês 3ª e 5ª- 09:40 às 11:20'], ['15:30 às 17:10', 'Inglês 3ª e 5ª- 15:30 às 17:10'], ['17:10 às 18:50', 'Inglês 3ª e 5ª- 17:10 às 18:50'], ['17:10 às 18:50', 'Japonês 2ª e 4ª- 17:10 às 18:50']], max_length=25, verbose_name='Horário')),
                ('curso2', models.CharField(blank=True, choices=[['Alemão', 'Alemão'], ['Espanhol', 'Espanhol'], ['Francês', 'Francês'], ['Inglês', 'Inglês'], ['Italiano', 'Italiano'], ['Japonês', 'Japonês']], max_length=45, null=True, verbose_name='Nome do Curso 2')),
                ('turma2', models.CharField(blank=True, max_length=3, null=True, verbose_name='Turma')),
                ('dia_semana2', models.CharField(blank=True, choices=[['Terça e Quinta', 'Alemão - Terça e Quinta'], ['Segunda e Quarta', 'Espanhol - Segunda e Quarta'], ['Terça e Quinta', 'Espanhol - Terça e Quinta'], ['Terça e Quinta', 'Francês - Terça e Quinta'], ['Terça e Quinta', 'Italiano - Terça e Quinta'], ['Segunda e Quarta', 'Inglês - Segunda e Quarta'], ['Terça e Quinta', 'Inglês - Terça e Quinta'], ['Segunda e Quarta', 'Japonês - Segunda e Quarta']], max_length=45, null=True, verbose_name='Dia da Semana')),
                ('horario2', models.CharField(blank=True, choices=[['17:10 às 18:50', 'Alemão 3ª e 5ª- 17:10 às 18:50'], ['08:00 às 09:40', 'Espanhol 2ª e 4ª- 08:00 às 09:40'], ['17:10 às 18:50', 'Espanhol 2ª e 4ª- 17:10 às 18:50'], ['19:10 às 20:50', 'Espanhol 2ª e 4ª- 19:10 às 20:50'], ['15:30 às 17:10', 'Espanhol 3ª e 5ª- 15:30 às 17:10'], ['17:10 às 18:50', 'Espanhol 3ª e 5ª- 17:10 às 18:50'], ['08:00 às 09:40', 'Francês 3ª e 5ª- 08:00 às 09:40'], ['19:10 às 20:50', 'Francês 3ª e 5ª- 19:10 às 20:50'], ['13:30 às 15:10', 'Italiano 3ª e 5ª- 13:30 às 15:10'], ['17:10 às 18:50', 'Inglês 2ª e 4ª- 17:10 às 18:50'], ['19:10 às 20:50', 'Inglês 2ª e 4ª- 19:10 às 20:50'], ['09:40 às 11:20', 'Inglês 3ª e 5ª- 09:40 às 11:20'], ['15:30 às 17:10', 'Inglês 3ª e 5ª- 15:30 às 17:10'], ['17:10 às 18:50', 'Inglês 3ª e 5ª- 17:10 às 18:50'], ['17:10 às 18:50', 'Japonês 2ª e 4ª- 17:10 às 18:50']], max_length=25, null=True, verbose_name='Horário')),
            ],
            options={
                'db_table': 'inscricao',
                'managed': False,
            },
        ),
    ]
