# Generated by Django 3.2.8 on 2021-11-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': False, 'verbose_name_plural': 'alunos'},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'managed': False, 'verbose_name_plural': 'contatos'},
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'managed': False, 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterModelOptions(
            name='eestadual',
            options={'managed': False, 'verbose_name_plural': 'escolas'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'managed': False, 'verbose_name_plural': 'enderecos'},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'managed': False, 'verbose_name_plural': 'inscricoes'},
        ),
    ]
