# Generated by Django 3.2.7 on 2021-10-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemcel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.DeleteModel(
            name='Eestadual',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
